# # # # # # # # # # # # # # # # # # # # # # # # # #
#   ________                     __    ____  ___  #
#  /  _____/___________    _____/  |_  \   \/  /  #
# /   \  __\_  __ \__  \  /    \   __\  \     /   #
# \    \_\  \  | \// __ \|   |  \  |    /     \   #
#  \______  /__|  (____  /___|  /__|   /___/\  \  #
#         \/           \/     \/             \_/  #
# # # # # # # # # # # # # # # # # # # # # # # # # #
# |
# ---------------------------------------------------------------------------------------
# Welcome to the official durations editor menu config file for GrantX!
# This is where you can change how the duration selection menu for the editor looks.
# If you are unsure of what something does: https://demeng.dev/grantx/docs
# Stuck? Getting errors? Contact out support team at https://demeng.dev/discord.
# Thank you for using GrantX!
# ---------------------------------------------------------------------------------------

config-version: 1

# The number of slots in the menu.
# Must be a multiple of nine, greater or equal to 9, and less than or equal to 54.
size: 54

# The title of the menu. Color codes are supported.
# Use %id% for the identifier of the duration being edited. Warning: It may go over Minecraft's 32 character limit!
title: "Editing Duration"

# The item that will be used for the GUI's background. Set to "AIR" for no background item.
background: "AIR"

# Configuration for the Info button.
info-button:
  # The slot of the button.
  slot: 5
  # The material of the button.
  material: "NAME_TAG"
  # The display name of the button. You can use the %id% placeholder for the duration's identifier.
  display-name: "&b&lYou are editing the &f&l%id% &b&lduration."
  # The lore of the button. Set as an empty list or put the first element as "none" to disable.
  lore: []
  # If this button should have a fake (hidden) enchantment.
  glow: true

# Configuration for the Change Weight button, used for changing the actual duration.
time-button:
  slot: 11
  material: "CLOCK"
  display-name: "&9&lChange Time"
  lore:
    - "&bClick to change time."
    - ""
    - "&7This is how long this duration lasts"
    - "&7after being granted."
    - ""
    - "&3Current: &f%current%"

# Configuration for the Change Weight button, used for changing the weight/priority of the duration.
weight-button:
  slot: 13
  material: "GOLD_INGOT"
  display-name: "&9&lChange Weight"
  lore:
    - "&bClick to change weight."
    - ""
    - "&7Duration weight determines the order of"
    - "&7which your durations are displayed in"
    - "&7paginated menus as well as many other"
    - "&7things. Generally, the higher the weight,"
    - "&7the longer the duration is."
    - ""
    - "&3Current: &f%current%"
  glow: false

# Configuration for the Change Slot button, used for changing the slot of the duration in the grant menu.
slot-button:
  slot: 15
  material: "HEAVY_WEIGHTED_PRESSURE_PLATE"
  display-name: "&9&lChange Slot"
  lore:
    - "&bClick to change slot."
    - ""
    - "&7This is which position the duration is displayed"
    - "&7in inside menus if it is not paginated. By"
    - "&7default, this setting is ignored unless you"
    - "&7make the grant menu a one-page menu in config."
    - ""
    - "&3Current: &f%current%"
  glow: false

# Configuration for the Change Material button, used for changing the material of the duration.
material-button:
  slot: 17
  material: "CRAFTING_TABLE"
  display-name: "&9&lChange Material"
  lore:
    - "&bClick to pick a material."
    - ""
    - "&7The material that represents this duration"
    - "&7in GUI menus."
    - ""
    - "&3Current: &f%current%"
  glow: false

# Configuration for the Change Display Name button, used for changing the display name of the duration.
display-name-button:
  slot: 20
  material: "OAK_SIGN"
  display-name: "&9&lChange Display Name"
  lore:
    - "&bClick to change display name."
    - ""
    - "&7Display name is the \"nicer\" form of the"
    - "&7duration's name. It is usually used in"
    - "&7GUIs and chat messages."
    - ""
    - "&3Current: &f%current%"
  glow: false

# Configuration for the Change Lore button, used for changing the lore of the duration in the grant menu.
lore-button:
  slot: 22
  material: "PAPER"
  display-name: "&9&lChange Lore"
  lore:
    - "&bLeft-click to add line."
    - "&bRight-click to remove line."
    - "&bShift-click to reset to default."
    - "&bSet as \"None\" to disable."
    - ""
    - "&7Lore is displayed in the durations's "
    - "&7button inside the grant GUI. By default,"
    - "&7the duration will use the default lore as"
    - "&7defined in menus/grant/durations.yml."
    - ""
    - "&3Current:"
    - "&f%current%"
  glow: false

# Configuration for the Change Permission button, used for changing the required permission to select the duration.
permission-button:
  slot: 24
  material: "BLAZE_POWDER"
  display-name: "&9&lChange Permission"
  lore:
    - "&bClick to change required permission."
    - "&bSet as \"None\" to disable."
    - ""
    - "&7This is the permission node that is required"
    - "&7to be able to select this duration. The"
    - "&7normal grantx.grant permission is still"
    - "&7required, this is just an additional"
    - "&7permission."
    - ""
    - "&3Current: &f%current%"
  glow: false

# Configuration for the Toggle Dummy button, used for toggling if the duration can be selected via the grant GUI.
dummy-button:
  slot: 26
  material: "BEDROCK"
  display-name: "&9&lToggle Dummy"
  lore:
    - "&bClick to toggle if this should be a dummy."
    - ""
    - "&7If No, the duration will be able to be"
    - "&7selected via the grant GUI. If Yes, the"
    - "&7duration will simply be for aesthetic"
    - "&7purposes."
    - ""
    - "&3Current: &f%current%"
  glow: false

# Configuration for the Toggle Glow button, used to toggle if the duration should have a fake enchant.
glow-button:
  slot: 30
  material: "ENCHANTMENT_TABLE"
  display-name: "&9&lToggle Glow"
  lore:
    - "&bClick to toggle glow."
    - ""
    - "&7Glow is simply a fake (hidden)"
    - "&7enchantment applied to the"
    - "&7duration's item in the grant GUI."
    - ""
    - "&3Current: &f%current%"
  glow: false

# Configure for the Change Blacklisted Servers button, used to pick which servers to hide the duration from.
blacklisted-servers-button:
  slot: 32
  material: "TNT"
  display-name: "&9&lChange Blacklisted Servers"
  lore:
    - "&bClick to change blacklisted servers."
    - ""
    - "&7This duration will be completely hidden"
    - "&7from all selected servers."
    - ""
    - "&3Current:"
    - "&f%current%"
  glow: false

# The button to delete the duration.
delete-button:
  slot: 34
  material: "ROSE_RED"
  display-name: "&4&lDelete Duration"
  lore:
    - "&cShift-click to delete this duration."
    - "&6This action is irreversible!"
  glow: false

# The button to go back to duration listings.
back-button:
  slot: 50
  material: "ARROW"
  display-name: "&cBack"
  lore:
    - "&7Go back to the previous menu."
  glow: false

# Configuration for the duration list menu, the menu where the duration to edit is chosen.
list-menu:
  # The number of slots in the menu (per page).
  # Must be a multiple of nine, greater or equal to 9, and less than or equal to 54.
  size: 54

  # The title of the menu. Color codes are supported.
  title: "Choose a Duration"

  # The item that will be used for the GUI's background. Set to "AIR" for no background item.
  background: "AIR"

  # Configuration for the separator, which is a row of items which separate the durations and page controls.
  separator:
    # Should GrantX add the separator?
    enabled: true
    # If the above setting is true- which of the GUI should the separator be in?
    row: 5
    # The material of the separator.
    material: "GRAY_STAINED_GLASS_PANE"

  # Configuration for the "previous page" button in the menu.
  previous-page-button:
    # The slot that this button will be in.
    slot: 46
    # The material of the button.
    material: "LIME_DYE"
    # The display name of the button.
    display-name: "&c< Previous Page"
    # The lore of the item. Set as an empty list or put the first element as "none" to disable.
    lore: []
    # If this item should have a fake (hidden) enchantment.
    glow: true
    # Overrides for the button if there are no more pages to go back to.
    no-more-pages:
      material: "GRAY_DYE"
      display-name: "&7You are on the first page."
      lore: []
      glow: false

  # Configuration for the "next page" button in the menu.
  next-page-button:
    slot: 54
    material: "LIME_DYE"
    display-name: "&aNext Page >"
    lore: []
    glow: true
    no-more-pages:
      material: "GRAY_DYE"
      display-name: "&7You are on the last page."
      lore: []
      glow: false

  # The range of slots that may contain durations.
  listing-range:
    # The first slot of each page that will contain a duration.
    start: 1
    # The last slot of each page that will contain a duration.
    end: 45

  # How each duration should be displayed in the menu.
  # Please check the wiki for a list of placeholders you can use for durations.
  duration-button:
    # Use %duration% for the duration's material.
    material: "%duration%"
    # Use %duration% for the name of the duration.
    display-name: "%duration%"
    # Set the first element to %duration% to get the lore of the duration.
    # Set as an empty list or put the first element as "none" to disable.
    lore:
      - "&bClick to edit this duration."
      - "&7&m-----------------------------------"
      - "&3&lCurrent Settings:"
      - "  &bID: &f%id%"
      - "  &bTime: &f%time%"
      - "  &bWeight: &f%weight%"
      - "  &bSlot: &f%slot%"
      - "  &bMaterial: &f%material%"
      - "  &bDisplay Name: &f%display-name%"
      - "  &bLore: &f%lore-type%"
      - "  &bPermission: &f%permission%"
      - "  &bDummy: &f%dummy%"
      - "  &bGlow: &f%glow%"
      - "  &bBlacklisted Servers: &f%blacklisted-servers-count%"
      - "&7&m-----------------------------------"
    glow: false

  # Configuration for the "Create Duration" button.
  create-button:
    slot: 49
    material: "EMERALD"
    display-name: "&9&lCreate Duration"
    lore:
      - "&bClick to create a new duration."
    glow: true

  # The button that goes back to the main menu.
  back-button:
    slot: 50
    material: "ARROW"
    display-name: "&cBack"
    lore:
      - "&7Go back to the previous menu."
    glow: false
